serviceAccount:
  name: thanos-role
objstoreConfig: |-
  type: s3
  config:
    bucket: dev-test-thanos-metrics-prometheus
    endpoint: s3.us-east-1.amazonaws.com
    sse_config:
      type: "SSE-S3"
query:
  dnsDiscovery:
    sidecarsService: kube-prometheus-prometheus-thanos
    sidecarsNamespace: platform
bucketweb:
  enabled: true
compactor:
  enabled: true
  serviceAccount:
    name: thanos-role
    create: false
storegateway:
  enabled: true
  serviceAccount:
    name: thanos-role
    create: false
ruler:
  enabled: true
  serviceAccount:
    name: thanos-role
    create: false
  alertmanagers:
    - http://kube-prometheus-alertmanager.monitoring.svc.cluster.local:9093
  config: |-
    groups:
      - name: "metamonitoring"
        rules:
          - alert: "PrometheusDown"
            expr: absent(up{prometheus="monitoring/kube-prometheus"})
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
